# Generated by Django 4.0.2 on 2022-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_bloguser_follower_remove_post_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
